version: '3'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: link_card
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/sql/init.sql:/docker-entrypoint-initdb.d/init.sql